// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/lyrics_model.dart';
import 'data/models/play_history_model.dart';
import 'data/models/playlist_model.dart';
import 'data/models/song_model.dart';
import 'data/models/stats_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 345115524638201753),
      name: 'AppSettings',
      lastPropertyId: const obx_int.IdUid(13, 7860704084997709216),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3361773200865013054),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3821400600328203803),
            name: 'themeMode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1351676073904694037),
            name: 'activeMood',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1290565645057537777),
            name: 'sakuraModeEnabled',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2197451127930519167),
            name: 'equalizerEnabled',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1676419710100716301),
            name: 'sleepTimerMinutes',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1268683211930417928),
            name: 'volumeLevel',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7779300936091592434),
            name: 'repeatMode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8801270463438364823),
            name: 'shuffleEnabled',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5975162044311824273),
            name: 'onboardingComplete',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 1755526775169324259),
            name: 'scanMinDurationSeconds',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7082717793105886830),
            name: 'excludedFoldersRaw',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 7860704084997709216),
            name: 'audioFocusPause',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 5767862606543212127),
      name: 'PlaylistModel',
      lastPropertyId: const obx_int.IdUid(8, 1438113582560312819),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2654343814812882999),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 342615998144754483),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8374259363042537581),
            name: 'coverImagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8705248288966875418),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8809752231158852330),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4029152823097042905),
            name: 'isSmartPlaylist',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8623788768987699127),
            name: 'smartPlaylistType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1438113582560312819),
            name: 'songOrderRaw',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 399750363943647580),
            name: 'songs',
            targetId: const obx_int.IdUid(3, 5057035137856442187))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5057035137856442187),
      name: 'SongModel',
      lastPropertyId: const obx_int.IdUid(15, 6426577670695010055),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 172610831957774495),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3328251537787421237),
            name: 'filePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8313596451425087519),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 135125333179760127),
            name: 'artist',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2330125034392154819),
            name: 'album',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2433111918665491815),
            name: 'genre',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2438878887876679752),
            name: 'year',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 9136700943124143590),
            name: 'trackNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3330805557644734875),
            name: 'durationMs',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4513888963812034284),
            name: 'albumArtPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 8162216670038673537),
            name: 'isFavorite',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6351160390115178392),
            name: 'playCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 6978144647976684782),
            name: 'lastPlayedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5622756046102456118),
            name: 'totalListenedMs',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 6426577670695010055),
            name: 'dateAdded',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 746373441526050355),
      name: 'PlayHistoryModel',
      lastPropertyId: const obx_int.IdUid(4, 7381891417638906214),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4652841338042730588),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8933552287391391095),
            name: 'songId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 3432400812631918064),
            relationTarget: 'SongModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8216531955370322396),
            name: 'timestamp',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7381891417638906214),
            name: 'durationMs',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 8618726821440492973),
      name: 'LyricsModel',
      lastPropertyId: const obx_int.IdUid(5, 4167036300643398846),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2016473293501535226),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2034938666280642057),
            name: 'songId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3941639178926228111),
            name: 'plainText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7794314534801873046),
            name: 'syncedLrc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4167036300643398846),
            name: 'fetchedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 8618726821440492973),
      lastIndexId: const obx_int.IdUid(1, 3432400812631918064),
      lastRelationId: const obx_int.IdUid(1, 399750363943647580),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSettings: obx_int.EntityDefinition<AppSettings>(
        model: _entities[0],
        toOneRelations: (AppSettings object) => [],
        toManyRelations: (AppSettings object) => {},
        getId: (AppSettings object) => object.id,
        setId: (AppSettings object, int id) {
          object.id = id;
        },
        objectToFB: (AppSettings object, fb.Builder fbb) {
          final themeModeOffset = fbb.writeString(object.themeMode);
          final activeMoodOffset = fbb.writeString(object.activeMood);
          final repeatModeOffset = fbb.writeString(object.repeatMode);
          final excludedFoldersRawOffset =
              fbb.writeString(object.excludedFoldersRaw);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, themeModeOffset);
          fbb.addOffset(2, activeMoodOffset);
          fbb.addBool(3, object.sakuraModeEnabled);
          fbb.addBool(4, object.equalizerEnabled);
          fbb.addInt64(5, object.sleepTimerMinutes);
          fbb.addFloat64(6, object.volumeLevel);
          fbb.addOffset(7, repeatModeOffset);
          fbb.addBool(8, object.shuffleEnabled);
          fbb.addBool(9, object.onboardingComplete);
          fbb.addInt64(10, object.scanMinDurationSeconds);
          fbb.addOffset(11, excludedFoldersRawOffset);
          fbb.addBool(12, object.audioFocusPause);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = AppSettings()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..themeMode = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..activeMood = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..sakuraModeEnabled =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false)
            ..equalizerEnabled =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false)
            ..sleepTimerMinutes =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0)
            ..volumeLevel =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0)
            ..repeatMode = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '')
            ..shuffleEnabled =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false)
            ..onboardingComplete =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false)
            ..scanMinDurationSeconds =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0)
            ..excludedFoldersRaw =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 26, '')
            ..audioFocusPause =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 28, false);

          return object;
        }),
    PlaylistModel: obx_int.EntityDefinition<PlaylistModel>(
        model: _entities[1],
        toOneRelations: (PlaylistModel object) => [],
        toManyRelations: (PlaylistModel object) =>
            {obx_int.RelInfo<PlaylistModel>.toMany(1, object.id): object.songs},
        getId: (PlaylistModel object) => object.id,
        setId: (PlaylistModel object, int id) {
          object.id = id;
        },
        objectToFB: (PlaylistModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final coverImagePathOffset = object.coverImagePath == null
              ? null
              : fbb.writeString(object.coverImagePath!);
          final smartPlaylistTypeOffset = object.smartPlaylistType == null
              ? null
              : fbb.writeString(object.smartPlaylistType!);
          final songOrderRawOffset = fbb.writeString(object.songOrderRaw);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, coverImagePathOffset);
          fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(4, object.updatedAt?.millisecondsSinceEpoch);
          fbb.addBool(5, object.isSmartPlaylist);
          fbb.addOffset(6, smartPlaylistTypeOffset);
          fbb.addOffset(7, songOrderRawOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = PlaylistModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..coverImagePath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0))
            ..updatedAt = updatedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(updatedAtValue)
            ..isSmartPlaylist =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false)
            ..smartPlaylistType = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..songOrderRaw = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 18, '');
          obx_int.InternalToManyAccess.setRelInfo<PlaylistModel>(object.songs,
              store, obx_int.RelInfo<PlaylistModel>.toMany(1, object.id));
          return object;
        }),
    SongModel: obx_int.EntityDefinition<SongModel>(
        model: _entities[2],
        toOneRelations: (SongModel object) => [],
        toManyRelations: (SongModel object) => {},
        getId: (SongModel object) => object.id,
        setId: (SongModel object, int id) {
          object.id = id;
        },
        objectToFB: (SongModel object, fb.Builder fbb) {
          final filePathOffset = fbb.writeString(object.filePath);
          final titleOffset = fbb.writeString(object.title);
          final artistOffset =
              object.artist == null ? null : fbb.writeString(object.artist!);
          final albumOffset =
              object.album == null ? null : fbb.writeString(object.album!);
          final genreOffset =
              object.genre == null ? null : fbb.writeString(object.genre!);
          final albumArtPathOffset = object.albumArtPath == null
              ? null
              : fbb.writeString(object.albumArtPath!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, filePathOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, artistOffset);
          fbb.addOffset(4, albumOffset);
          fbb.addOffset(5, genreOffset);
          fbb.addInt64(6, object.year);
          fbb.addInt64(7, object.trackNumber);
          fbb.addInt64(8, object.durationMs);
          fbb.addOffset(9, albumArtPathOffset);
          fbb.addBool(10, object.isFavorite);
          fbb.addInt64(11, object.playCount);
          fbb.addInt64(12, object.lastPlayedAt?.millisecondsSinceEpoch);
          fbb.addInt64(13, object.totalListenedMs);
          fbb.addInt64(14, object.dateAdded.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastPlayedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final object = SongModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..filePath = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..artist = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..album = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..genre = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14)
            ..year =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16)
            ..trackNumber =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18)
            ..durationMs =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0)
            ..albumArtPath = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22)
            ..isFavorite =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false)
            ..playCount =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0)
            ..lastPlayedAt = lastPlayedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastPlayedAtValue)
            ..totalListenedMs =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0)
            ..dateAdded = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0));

          return object;
        }),
    PlayHistoryModel: obx_int.EntityDefinition<PlayHistoryModel>(
        model: _entities[3],
        toOneRelations: (PlayHistoryModel object) => [object.song],
        toManyRelations: (PlayHistoryModel object) => {},
        getId: (PlayHistoryModel object) => object.id,
        setId: (PlayHistoryModel object, int id) {
          object.id = id;
        },
        objectToFB: (PlayHistoryModel object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.song.targetId);
          fbb.addInt64(2, object.timestamp.millisecondsSinceEpoch);
          fbb.addInt64(3, object.durationMs);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = PlayHistoryModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..timestamp = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0))
            ..durationMs =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.song.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.song.attach(store);
          return object;
        }),
    LyricsModel: obx_int.EntityDefinition<LyricsModel>(
        model: _entities[4],
        toOneRelations: (LyricsModel object) => [],
        toManyRelations: (LyricsModel object) => {},
        getId: (LyricsModel object) => object.id,
        setId: (LyricsModel object, int id) {
          object.id = id;
        },
        objectToFB: (LyricsModel object, fb.Builder fbb) {
          final plainTextOffset = object.plainText == null
              ? null
              : fbb.writeString(object.plainText!);
          final syncedLrcOffset = object.syncedLrc == null
              ? null
              : fbb.writeString(object.syncedLrc!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.songId);
          fbb.addOffset(2, plainTextOffset);
          fbb.addOffset(3, syncedLrcOffset);
          fbb.addInt64(4, object.fetchedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = LyricsModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..songId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
            ..plainText = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..syncedLrc = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..fetchedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// See [AppSettings.id].
  static final id =
      obx.QueryIntegerProperty<AppSettings>(_entities[0].properties[0]);

  /// See [AppSettings.themeMode].
  static final themeMode =
      obx.QueryStringProperty<AppSettings>(_entities[0].properties[1]);

  /// See [AppSettings.activeMood].
  static final activeMood =
      obx.QueryStringProperty<AppSettings>(_entities[0].properties[2]);

  /// See [AppSettings.sakuraModeEnabled].
  static final sakuraModeEnabled =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[3]);

  /// See [AppSettings.equalizerEnabled].
  static final equalizerEnabled =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[4]);

  /// See [AppSettings.sleepTimerMinutes].
  static final sleepTimerMinutes =
      obx.QueryIntegerProperty<AppSettings>(_entities[0].properties[5]);

  /// See [AppSettings.volumeLevel].
  static final volumeLevel =
      obx.QueryDoubleProperty<AppSettings>(_entities[0].properties[6]);

  /// See [AppSettings.repeatMode].
  static final repeatMode =
      obx.QueryStringProperty<AppSettings>(_entities[0].properties[7]);

  /// See [AppSettings.shuffleEnabled].
  static final shuffleEnabled =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[8]);

  /// See [AppSettings.onboardingComplete].
  static final onboardingComplete =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[9]);

  /// See [AppSettings.scanMinDurationSeconds].
  static final scanMinDurationSeconds =
      obx.QueryIntegerProperty<AppSettings>(_entities[0].properties[10]);

  /// See [AppSettings.excludedFoldersRaw].
  static final excludedFoldersRaw =
      obx.QueryStringProperty<AppSettings>(_entities[0].properties[11]);

  /// See [AppSettings.audioFocusPause].
  static final audioFocusPause =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[12]);
}

/// [PlaylistModel] entity fields to define ObjectBox queries.
class PlaylistModel_ {
  /// See [PlaylistModel.id].
  static final id =
      obx.QueryIntegerProperty<PlaylistModel>(_entities[1].properties[0]);

  /// See [PlaylistModel.name].
  static final name =
      obx.QueryStringProperty<PlaylistModel>(_entities[1].properties[1]);

  /// See [PlaylistModel.coverImagePath].
  static final coverImagePath =
      obx.QueryStringProperty<PlaylistModel>(_entities[1].properties[2]);

  /// See [PlaylistModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<PlaylistModel>(_entities[1].properties[3]);

  /// See [PlaylistModel.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<PlaylistModel>(_entities[1].properties[4]);

  /// See [PlaylistModel.isSmartPlaylist].
  static final isSmartPlaylist =
      obx.QueryBooleanProperty<PlaylistModel>(_entities[1].properties[5]);

  /// See [PlaylistModel.smartPlaylistType].
  static final smartPlaylistType =
      obx.QueryStringProperty<PlaylistModel>(_entities[1].properties[6]);

  /// See [PlaylistModel.songOrderRaw].
  static final songOrderRaw =
      obx.QueryStringProperty<PlaylistModel>(_entities[1].properties[7]);

  /// see [PlaylistModel.songs]
  static final songs = obx.QueryRelationToMany<PlaylistModel, SongModel>(
      _entities[1].relations[0]);
}

/// [SongModel] entity fields to define ObjectBox queries.
class SongModel_ {
  /// See [SongModel.id].
  static final id =
      obx.QueryIntegerProperty<SongModel>(_entities[2].properties[0]);

  /// See [SongModel.filePath].
  static final filePath =
      obx.QueryStringProperty<SongModel>(_entities[2].properties[1]);

  /// See [SongModel.title].
  static final title =
      obx.QueryStringProperty<SongModel>(_entities[2].properties[2]);

  /// See [SongModel.artist].
  static final artist =
      obx.QueryStringProperty<SongModel>(_entities[2].properties[3]);

  /// See [SongModel.album].
  static final album =
      obx.QueryStringProperty<SongModel>(_entities[2].properties[4]);

  /// See [SongModel.genre].
  static final genre =
      obx.QueryStringProperty<SongModel>(_entities[2].properties[5]);

  /// See [SongModel.year].
  static final year =
      obx.QueryIntegerProperty<SongModel>(_entities[2].properties[6]);

  /// See [SongModel.trackNumber].
  static final trackNumber =
      obx.QueryIntegerProperty<SongModel>(_entities[2].properties[7]);

  /// See [SongModel.durationMs].
  static final durationMs =
      obx.QueryIntegerProperty<SongModel>(_entities[2].properties[8]);

  /// See [SongModel.albumArtPath].
  static final albumArtPath =
      obx.QueryStringProperty<SongModel>(_entities[2].properties[9]);

  /// See [SongModel.isFavorite].
  static final isFavorite =
      obx.QueryBooleanProperty<SongModel>(_entities[2].properties[10]);

  /// See [SongModel.playCount].
  static final playCount =
      obx.QueryIntegerProperty<SongModel>(_entities[2].properties[11]);

  /// See [SongModel.lastPlayedAt].
  static final lastPlayedAt =
      obx.QueryDateProperty<SongModel>(_entities[2].properties[12]);

  /// See [SongModel.totalListenedMs].
  static final totalListenedMs =
      obx.QueryIntegerProperty<SongModel>(_entities[2].properties[13]);

  /// See [SongModel.dateAdded].
  static final dateAdded =
      obx.QueryDateProperty<SongModel>(_entities[2].properties[14]);
}

/// [PlayHistoryModel] entity fields to define ObjectBox queries.
class PlayHistoryModel_ {
  /// See [PlayHistoryModel.id].
  static final id =
      obx.QueryIntegerProperty<PlayHistoryModel>(_entities[3].properties[0]);

  /// See [PlayHistoryModel.song].
  static final song = obx.QueryRelationToOne<PlayHistoryModel, SongModel>(
      _entities[3].properties[1]);

  /// See [PlayHistoryModel.timestamp].
  static final timestamp =
      obx.QueryDateProperty<PlayHistoryModel>(_entities[3].properties[2]);

  /// See [PlayHistoryModel.durationMs].
  static final durationMs =
      obx.QueryIntegerProperty<PlayHistoryModel>(_entities[3].properties[3]);
}

/// [LyricsModel] entity fields to define ObjectBox queries.
class LyricsModel_ {
  /// See [LyricsModel.id].
  static final id =
      obx.QueryIntegerProperty<LyricsModel>(_entities[4].properties[0]);

  /// See [LyricsModel.songId].
  static final songId =
      obx.QueryIntegerProperty<LyricsModel>(_entities[4].properties[1]);

  /// See [LyricsModel.plainText].
  static final plainText =
      obx.QueryStringProperty<LyricsModel>(_entities[4].properties[2]);

  /// See [LyricsModel.syncedLrc].
  static final syncedLrc =
      obx.QueryStringProperty<LyricsModel>(_entities[4].properties[3]);

  /// See [LyricsModel.fetchedAt].
  static final fetchedAt =
      obx.QueryDateProperty<LyricsModel>(_entities[4].properties[4]);
}
